version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Nicolas123.
      POSTGRES_DB: mi_base
    ports:
      - "15433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: